version: "3.8"

networks:
  default:
    external:
      name: backend
services:
  mydb:
    image: mongo:latest
    container_name: mydb
    ports:
      - 27017:27017
  ibm-demo-image:
    image: ibm-demo-app-image
    container_name: ibm-demo-image
    ports:
      - 8081:8081
    links:
      - mydb