version: "3.3"

services:
  mydb:
    image: mongo:latest
    container_name: mydb
    ports:
      - 27017:27017
  ibm-demo-backend:
    image: ferryxo/ibm-demo-backend
    container_name: ibm-demo-backend-container
    ports:
      - 8081:8081
    links:
      - mydb
